language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
before_script:
  - npm install -g @vue/cli
install:
  - npm install
cache:
  directories:
    - node_modules
stages:
  - lint
  - test
  - build
  - deploy
    if: branch = master
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      name: unit
      script:
        - npm run test:unit
    - stage: build
      script:
        - npm run serve
    - stage: deploy
      script:
        - npm run serve
      deploy:
        provider: firebase
        skip_cleanup: true
        token: $FIREBASE_TOKEN
        message: "Deployed from Travis CI"
        local_dir: dist/
        on:
          branch: master
