language: node_js
node_js:
  - lts/*
addons:
  apt:
    packages:
      - libgconf-2-4 # Cypress dependency
branches:
  only:
    - master
notifications:
  email: false
before_script:
  - npm install -g @vue/cli
install:
  - npm install
cache:
  directories:
    - node_modules
    - ~/.cache # Cypress binary
script:
  - npm run lint
  - npm run test:unit
  - npm run build
after_script:
  - cat ./coverage/lcov.info | coveralls
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  message: "Deployed from Travis CI"
  local_dir: dist/
  on:
    branch: master