language: node_js

node_js:
  - lts/*

addons:
  apt:
    packages:
      - libgconf-2-4 # Cypress dependency

branches:
  only:
    - master
    - development

notifications:
  email: false

before_script:
  - npm install -g @vue/cli

install:
  - npm install

cache:
  directories:
    - node_modules
    - ~/.cache # Cypress binary

stages:
  - test
  - deploy

jobs:
  include:
    - stage: test
      name: "Unit Tests"
      script:
        - npm run test:unit
    - name: "Integration Tests"
      script:
        - npm run test:e2e -- --headless
    - stage: deploy
      name: "Deploy to Firebase"
      script:
        - npm run build
      after_script:
        - cat ./coverage/lcov.info | coveralls
      deploy:
        provider: firebase
        skip_cleanup: true
        token: $FIREBASE_TOKEN
        message: "Deployed from Travis CI"
        local_dir: dist/
        on:
          branch: master