language: node_js
node_js:
  - lts/*
branches:
  only:
    - master
before_script:
  - npm install -g @vue/cli
install:
  - npm install
cache:
  directories:
    - node_modules
script:
  - npm run lint
  - npm run test:unit
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  message: "Deployed from Travis CI"
  local_dir: dist/
  on:
    branch: master